:sectnums:

= parent-pom


image:https://github.com/innovitech-org/parent-pom/actions/workflows/compile.yml/badge.svg?style=plastic&branch=main[GitHub Compile workflow status in master branch]
image:https://img.shields.io/maven-central/v/hu.innovitech.pom/parent-pom?logo=apache-maven&style=for-the-badge)[Maven central version of Parent pom project]
image:https://img.shields.io/github/license/innovitech-org/parent-pom?style=plastic&logo=apache[License of Parent pom project]
image:https://img.shields.io/badge/JVM-11,17,21-brightgreen.svg?style=plastic&logo=openjdk[Supported JVM Versions]

Általános maven fő pom.xml, amit minden InnovITech Kft. projekt tartalmaz.

A projekt célja, hogy a cégben a projektek azonos általános beállításokkal működjenek.
Összegyűjti a közös beállításokat, azonosítókat így elkerülhető a fejlesztői beállítások összeakadása.
Továbbá segít frissen tartani a plugineket, bugok esetén közös workaround-ot tesz lehetővé.


== Maven central
A projekt buildelve van a official maven repository-ba is,
így a projektek automatán lehúzzák:

.Általános beállítások
[source, xml]
----
    <dependency>
        <groupId>hu.innovitech.pom</groupId>
        <artifactId>parent-pom</artifactId>
        <version>${version}</version>
    </dependency>
----

.innovitech nexus beállítások
[source, xml]
----
    <dependency>
        <groupId>hu.innovitech.pom</groupId>
        <artifactId>parent-innovitech-pom</artifactId>
        <version>${version}</version>
    </dependency>
----

.innovitech open-source projektek beállítása
[source, xml]
----
    <dependency>
        <groupId>hu.innovitech.pom</groupId>
        <artifactId>parent-oss-pom</artifactId>
        <version>${version}</version>
    </dependency>
----

== Leírás
Bővebb leírás a https://innovitech-org.github.io/parent-pom/ oldalon található.
