# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      comment:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Comment for deploy'
        # Default value if no value is explicitly provided
        default: 'Deploy SNAPSHOT from WEB UI'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure GIT for signed commit
      env:
        # GPG kulcs azonositoja
        GPG_KEY_ID_GITHUB_TECHUSER: ${{ secrets.GPG_KEY_ID_GITHUB_TECHUSER }}
      run: |
        git config --global user.name "Innovitech-admin"
        git config --global user.email "github-techuser@innovitech.hu"
        git config --global user.signingkey "$GPG_KEY_ID_GITHUB_TECHUSER"
        git config --global commit.gpgsign true
        git config --global tag.gpgSign true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: ${{ secrets.OSS_SONATYPE_ORG_USER }}
        server-password: ${{ secrets.OSS_SONATYPE_ORG_PASSWORD }}
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B -Pparent-pom-release deploy -DskipStaging=true -Dgpg.skip=true -s $GITHUB_WORKSPACE/.github/.m2/settings.xml
      env:
        GITHUB_TOKEN: '${{ secrets.GH_TOKEN_TECHUSER_JAVA }}'
        OSSRH_USERNAME: '${{ secrets.OSS_SONATYPE_ORG_USER }}'
        OSSRH_PASSWORD: '${{ secrets.OSS_SONATYPE_ORG_PASSWORD }}'
